// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EchartBasic: typeof import('./components/EchartBasic/Index.vue')['default']
    GaodeMapCom: typeof import('./components/GaodeMapCom.vue')['default']
    IconifyCom: typeof import('./components/IconifyCom.vue')['default']
    MdEditorV3Com: typeof import('./components/MdEditorV3Com.vue')['default']
    RichTextCom: typeof import('./components/RichTextCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgFileCom: typeof import('./components/SvgFileCom.vue')['default']
    VAdminTable: typeof import('./components/VAdminTable/Index.vue')['default']
  }
}

export {}
